Events route tests
KnightHacks/hackathon-2021-backend pull request #2
Opened 2021-05-17 04:19 UTC by Astatium5

2021-05-19 01:50 UTC, AdamPellot commented on src/api/events.py
> +            data["end_date_time"] = dateutil.parser.parse(data["end_date_time"])
Fix this line too long issue

2021-05-19 01:52 UTC, AdamPellot requested changes
Everything looks good just fix the "line too long" issue the linter caught.

2021-05-19 01:59 UTC, Astatium5 commented on src/api/events.py
> +            data["end_date_time"] = dateutil.parser.parse(data["end_date_time"])
I am not sure how to fix it in this case.

2021-05-30 14:42 UTC, AdamPellot approved these changes
Nice job

2021-05-30 14:42 UTC, merged