Email templates
KnightHacks/hackathon-2021-backend pull request #65
Opened 2021-10-09 21:50 UTC by TorrentofShame

Updates and adds templates as provided by @APherwani, updates and adds helper functions as applicable.
Adds static files, (temporary solution, should have static assets hosted on a CDN in the future)

- resolves: #47 
- resolves: #48 

Checklist:

- [x] Add or update the relevant docs.
- [x] Add an entry in `CHANGELOG.md` summarizing the change.
- [x] Run tests, with no tests failed.

2021-10-09 23:37 UTC, APherwani requested changes
Just some minor things. Looks great otherwise! Thanks Simon.

2021-10-09 23:37 UTC, APherwani commented on src/common/mail.py
> +                     "Thank You for Confirming Your Attendance!"),
I don't think the subject should be "Knight Hacks - John Smith, Thank You for Confirming Your Attendance!".
There's two issues I see with it:
1. The capitalization is non-standard
2. I don't think it's necessary to include the hackers first name in the subject line.

2021-10-09 23:37 UTC, APherwani commented on src/common/mail.py
>      if not currapp.config.get("TESTING"):
Is the established pattern to do this instead of:
if curapp.config["SEND_MAIL"] ?
The latter makes more sense to me, but if this is an established pattern leave it.

2021-10-09 23:37 UTC, APherwani commented on src/templates/emails/email_verification.html
>         <a href="{{href}}">Click Here</a>
Nit: Align this and the bottom component

2021-10-09 23:41 UTC, APherwani commented
One more thing, can you send me an email from both templates as an additional sanity check. You have my email.

2021-10-09 23:44 UTC, TorrentofShame commented on src/common/mail.py
> +                     "Thank You for Confirming Your Attendance!"),
So, "Knight Hacks - Thank you for confirming!"?

2021-10-09 23:46 UTC, TorrentofShame commented on src/common/mail.py
>      if not currapp.config.get("TESTING"):
Established pattern, it allows for cleaner code as you don't need to indent everything after it.

2021-10-09 23:48 UTC, APherwani commented on src/common/mail.py
>      if not currapp.config.get("TESTING"):
wait don't you indent everything after testing?

2021-10-09 23:57 UTC, TorrentofShame commented
> One more thing, can you send me an email from both templates as an additional sanity check. You have my email.

I can; however, the static assets will not render as that required the backend to be updated with this pr.

2021-10-10 00:01 UTC, APherwani approved these changes
LGTM

2021-10-10 00:03 UTC, merged